// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/CandyPop.tsx": () => import("../components/mockups/themes/CandyPop.tsx"),
  "./components/mockups/themes/CosmicKids.tsx": () => import("../components/mockups/themes/CosmicKids.tsx"),
  "./components/mockups/themes/RainbowBurst.tsx": () => import("../components/mockups/themes/RainbowBurst.tsx")
};
